version: '3.4'

services:
  backend:
    build:
      context: .
      target: php-fpm
      args:
        - WITH_XDEBUG=true
    volumes:
      - .:/var/www
    links:
      - database
    environment:
      APP_ENV: dev
      PHP_OPCACHE: 0
      XDEBUG_CONFIG: client_host=172.17.0.1
      DATABASE_URL: pgsql://da4a:qwerty@database:5432/shop
    entrypoint: .docker/fpm/bootstrap.dev.sh

  database:
    image: postgres:alpine
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: da4a
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: shop

  nginx:
    image: "nginx"
    volumes:
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 81:80
    links:
      - backend
    environment:
      - APP_ENTRYPOINT=/var/www/public/index.php
      - FPM_UPSTREAM=backend:9000
